#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

clear
echo "-----------------"
echo "-    welcome!   -"
echo "-----------------"

exec setsid cttyhack sh
